[package]
name = "sentinel"
version = "0.1.0"
authors = ["MuZhou233 <muzhou233@outlook.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2021"

[dependencies]
tonic = "0.7"
prost = "0.10"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
log = "0.4.14"
structopt = "0.3"
walkdir = "2"

[build-dependencies]
tonic-build = "0.7"

[profile.release]
lto = true
strip = true
panic = "abort"